# This file is automatically generated.
# It contains project source information necessary for synthesis and implementation.

# IP: ip/memory/memory.xco
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==memory || ORIG_REF_NAME==memory} -quiet] -quiet

# Block Designs: bd/design_1/design_1.bd
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==design_1 || ORIG_REF_NAME==design_1} -quiet] -quiet

# Block Designs: bd/design_2/design_2.bd
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==design_2 || ORIG_REF_NAME==design_2} -quiet] -quiet

# XDC: bd/design_1/design_1_ooc.xdc

# XDC: bd/design_2/design_2_ooc.xdc
